#!/usr/bin/env python3

PROJECT_PATH = '<ENTER HERE THE ABSOLUT PATH TO YOUR PROJECT>'
TEMPERATURE_DATA_FILE = PROJECT_PATH + "/Data/temperature.csv"
LOGFILE_WITH_PATH = PROJECT_PATH + "/DataRepository.log"
####### TEST FILES

PROJECT_TEST_PATH = '<ENTER HERE THE ABSOLUT PATH TO YOUR TEST PROJECT>'
TEST_TEMPERATURE_DATA_FILE = "/Data/temperature_test.csv"
