# TEMPERATURE IN CELSIUS DEGREE
# modify the temperature value to the value you need

TEMPERATURE_LIMITS = {
    "SETPOINT": 24,
    "WARNING": 25,
    "ALERT": 26
}

WATER_SENSOR_ID = "<SENSOR_ADDRESS>"
AMBIETEN_SENSOR_ID = "<SENSOR_ADDRESS>"
SOIL_TEMPERATURE_SENSOR_ID = "<SENSOR_ADDRESS>"